### PR TITLE
Add the extension dependency of json

### PR DESCRIPTION
**Pull request by guanguans**
* [Add the extension dependency of json](https://github.com/adhocore/php-json-fixer/commit/54bc4cc16253b6ae1c2049a13a6383d256d1b048)
* [Fix typo](https://github.com/adhocore/php-json-fixer/commit/a97811df633bc5909a099d7d89558c45d6da238f)

### CODE REVIEW

**Comment by adhocore** [comment]
thank you, Travis seems failing. if you could paste in screenshot of tests passing then we are good to go.
(later we can move to GitHub actions for tests)

**Comment by guanguans** [comment]
I'm sorry.

**Comment by adhocore** [comment]
no need to sorry. the PR is good :) 
pls make build pass so we can merge it. thank you 💯

**Comment by guanguans** [comment]
For compatibility with differences between php and phpunit versions, I remove the method of `setUp`. 
The [build](https://github.com/guanguans/php-json-fixer/actions/runs/3590211944) of action has passed. 

##

```diff
--protected function setUp()
++protected function setUp(): void
{
}
```

**Comment by adhocore** [comment]
thanks 👍

**Pull request merged**
